project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: false

website:
  title: "EStaSys"
  open-graph:
    locale: id_ID
    site-name: EStaSys - Belajar Data Science
    description: |
      EStaSys (Efficience Statistical and Analysis) adalah catatan tentang data
       science terkait apa yang sudah penulis pelajari secara mandiri dari
       berbagai referensi seperti buku, e-course, webinar, dan bootcamp.
  page-navigation: true
  twitter-card: true
  favicon: favicon.svg
  repo-url: https://github.com/estasys/estasys
  repo-actions: [edit, issue]
  page-footer:
    left: |
      © 2023
      <a href="https://hervyqa.id" target="_blank">Hervy Qurrotul A.</a>
    right:
      - text: "Profil"
        href: profil.qmd
      - text: "Lisensi"
        href: lisensi.qmd

  navbar:
    background: dark
    logo: logo.svg
    logo-alt: "EStaSys"
    title: false
    collapse-below: lg
    left:
      - text: Pembukaan
        href: index.qmd
      - text: Python
        href: python.qmd
      - text: R
        href: r.qmd
      - text: Julia
        href: julia.qmd
      - text: SQL
        href: sql.qmd
      - text: Scala
        href: scala.qmd
      - text: Markdown
        href: markdown.qmd

  sidebar:
    - id: "start"
      title: "Persiapan"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: Pendahuluan
          href: index.qmd
        - section: "Persiapan teknis"
          contents:
          - spesifikasi-komputer.qmd
          - bahasa-pemrograman.qmd
          - sistem-operasi.qmd
          - ide-software.qmd
          - teks-editor.qmd
        - section: "Strategi pembelajaran"
          contents:
          - manajemen-waktu.qmd
          - motivasi-belajar.qmd
          - bahasa-internasional.qmd

    - id: "python"
      title: "Python"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: Pendahuluan
          href: python.qmd
        - section: "Dasar Python"
          contents:
          - python.qmd

    - id: "r"
      title: "R"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: Pendahuluan
          href: r.qmd
        - section: "Dasar R"
          contents:
          - r.qmd

    - id: "julia"
      title: "Julia"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: Pendahuluan
          href: julia.qmd
        - section: "Dasar Julia"
          contents:
          - julia.qmd

    - id: "sql"
      title: "SQL"
      style: "docked"
      collapse-level: 2
      contents:
        - text: Pendahuluan
          href: sql.qmd
        - section: "Dasar MySQL"
          contents:
          - sql.qmd

    - id: "scala"
      title: "Scala"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: Pendahuluan
          href: scala.qmd
        - section: "Dasar Scala"
          contents:
          - scala.qmd

    - id: "markdown"
      title: "Markdown"
      style: "docked"
      collapse-level: 2
      align: left
      contents:
        - text: Pendahuluan
          href: markdown.qmd
        - section: "Dasar Markdown"
          contents:
          - markdown.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: visual
