---
title: "Manajemen waktu"
---

### Rencana waktu belajar

Target rencana belajar tidak perlu tinggi, tetapi konsisten dengan apa yang dipelajari.
Waktu efektif untuk belajar yaitu 6 bulan atau sekitar 2 jam perhari.

```{mermaid}
journey
    section Bulan 1-2
      Teori Kelas: 3: Individu
    section Bulan 3
      Praktek: 3: Individu, Team
    section Bulan 4
      Evaluasi: 4: Individu, Team
    section Bulan 5
      Portofolio: 5: Individu
    section Bulan 6
      Magang & Kontes: 5: Individu, Team
```

### Membuat peta materi belajar

Panduan ini penulis mencoba untuk membuat kurikulum sebagai *programmer* pemula.
Untuk tingkatan lanjut perlu memilih dan memilah materi mana yang sesuai dengan kebutuhan acuan belajar sehingga jalur pembelajaran menjadi jelas.
Saat ini belum ada *learning path* khusus, hanya tersedia satu jalur (R > Python > SQL > dan seterusnya).

```{mermaid}
graph TD
  coding{Koding}
  coding --> r(R)
  coding --> py(Python)
  coding --> jl(Julia)
  coding --> sql(SQL)
  coding --> scl(Scala)
  coding --> md(Markdown)
```

### Aturan imbalan atau sanksi

Tergantung kesepakatan dengan diri sendiri, penghargaan atau hukuman dapat diberikan jika telah menyelesaikan materi yang ditentukan.
Hal ini melatih tanggung jawab agar sesuai dengan target belajar yang telah ditentukan sebelumnya.

### Tidak menunda aktifitas

Kembali lagi ke individunya masing-masing. Konsisten itu penting.

### Tidak berharap sempurna

Setiap pembelajaran butuh proses yang tidak instan, terkadang perlu mencoba berkali-kali agar lebih memahami materi.

### Lakukan evaluasi secara berkala

Pentingnya evaluasi untuk menganalisa kekurangan apa saja yang perlu diperbaiki.
Misalnya ada materi atau istilah di bagian sub-bab yang masih belum dimengerti untuk dibaca ulang.
Terlebih lagi jika ada *syntax* yang tidak sesuai antara materi dengan hasil keluaran saat praktik langsung.
