---
  title: "Sistem Operasi"
---

## Pengertian sistem operasi

Sistem operasi (*operating system*) adalah perangkat lunak sistem yang mengatur perangkat keras dan perangkat lunak agar dapat menjalankan program komputer di perangkat pengguna. Di dalam sistem operasi, terdapat *kernel/driver* yang menjalankan program inti sistem operasi untuk menghubungkan akses ke disk, memori, tampilan, antarmuka dan perangkat keras lainnya.

## Jenis sistem operasi

* *GNU/Linux*.
* Apple macOS.
* Microsoft Windows.

Ada beberapa sistem operasi lainnya seperti BSD, Redox dan Haiku. Tetapi penulis menyarankan untuk menggunakan sistem operasi di atas yang lebih kompatibel.

## Memilih sistem operasi

Ada banyak pertimbangan untuk memilih sistem operasi yang mendukung kebutuhan data science. Penulis menyarankan untuk menggunakan sistem operasi *GNU/Linux*. Alasannya yaitu:

* **Harga**, *GNU/Linux* adalah sistem operasi yang bisa didapatkan secara murah dan bahkan gratis.
* **Keamanan**, *GNU/Linux* relatif lebih aman dibandingkan sistem operasi lainnya dan tidak memerlukan antivirus atau sejenisnya.
* **Performa**, jika dibandingkan dengan spesifikasi perangkat keras yang sama, sistem operasi *GNU/Linux* memiliki performa yang lebih baik dalam komputasi.
* **Kustom**, *GNU/Linux* dapat dimodifikasi sesuai kebutuhan pengguna, baik secara tampilan dan konfigurasi sistem.
* **Komunitas**, banyak relawan dari komunitas *GNU/Linux* yang aktif memberikan dukungan secara cuma-cuma ke pengguna lainnya.

Kekhawatiran sebagai pengguna *GNU/Linux* yaitu masalah di kompatibilitas perangkat lunak pihak ketiga. Beberapa perangkat lunak di industri tidak menyediakan dukungan platform *GNU/Linux*, perangkat lunak ini disebut dengan *proprietary* atau perangkat lunak tidak bebas (*nonfree software*). Hal ini akan memaksa untuk menggunakan sistem operasi lainnya agar program tersebut dapat dijalankan.

## Memilih perangkat lunak pendukung

Perangkat lunak pendukung seperti *IDE*, teks editor, kompiler, dan sebagainya, juga perlu dipertimbangkan karena tidak semua perangkat lunak berhasil dipasang di sistem operasi tertentu.

Beberapa manufaktur dan vendor pengembang akan membuat perangkat lunak berdasarkan platform sesuai pasar produk mereka.
Sebelum menggunakan produk perangkat lunak pendukung, pastikan dapat berjalan di sistem operasi yang digunakan saat ini.
Hal inilah yang menjadikan seberapa pentingnya perangkat lunak terbuka (*free open source software*) agar dapat berjalan di platform manapun dan pengguna bebas menggunakannya tanpa terikat di sistem operasi tertentu.

Di dalam panduan belajar ini penulis menggunakan perangkat lunak terbuka agar dapat dipasang di sistem operasi *GNU/Linux*, macOS dan Windows.
